### ISSUE TITLE
Model subfolders

### ISSUE THREAD

**Issue by bebran** [archi-contribs/form-plugin#10]
Excellent work on the form plugin, but I'm struggling with displaying elements located in subfolders (ex. Application/subfolderXYZ/).
My models contains >3000 elements and depends on subfolders for grouping elements in the Models panel, but it seems like the forms plugin doesn't include/pick-up elements stored in subfolders.

**Comment by herve91** [comment]
This issue has been solved in the latest version.  Which version are you using ?

**Comment by bebran** [comment]
Very strange - I'm running on two different systems/installations and both fails to include elements placed in subfolders:
- MacOS 10.13.2, Archi 4.1.0, form plugin v. 1.8.3
- Win 7, Archi 4.1.0, form plugin v. 1.8.3

I'm using the demo configuration file from GitHub (which by the way will not accept line 227), and only elements placed in the root folders will be displayed in the 'Elements placed in the container' tab.

Could it be a problem with the conf file - maybe you have another configuration file I could use for testing?

**Comment by herve91** [comment]
You'll have to wait few days as I'm on vacation for Christmas. I'll do some more testing and send you some sample files when I come back home.

**Comment by herve91** [comment]
Done, it will be part of the next release.

Best regards
Hervé

**Comment by bebran** [comment]
Hi Herve,
I have downloaded the latest version 1.8.4, but is still not able to list any objects placed in subfolders.
Could you please forward sample files (a model and a conf file) that you positively know works.
Thanks for your assistance.
Best regards
Bent

**Comment by herve91** [comment]
Hi Bent,

My apologies, I had forgotten one case. I released the version 1.8.5 which should solve it.

Could you please confirm ?

Thanks and regards
Hervé

**Comment by bebran** [comment]
Hi Herve,
Objects placed in subfolders are now listed as expected :+1:
Unfortunately, some of my models are quite big (+2000 objects) and the list seems to hang at times - not sure when, so I'll be playing around with the Java heap size and debug/trace logger.
/Bent

**Comment by herve91** [comment]
To allow to update information in the table, each table cell is a widget (text, combo, etc ...)

So if you've got 2000 rows with several columns, then it will effectively take a long time ...

I can add a popup with some information about what the plugin does during the form creation ... but I won't be able to make things go quicker I'm afraid ...

**Comment by herve91** [comment]
My apologies for this very long delay. The popup will be added in the next release 1.8.10.
